Added more details to list command.
GitDepend/GitDepend pull request #239
Opened 2017-04-10 17:31 UTC by bbirds

Why:
The list does not currently give a lot of useful information.
This change addresses the need by:
Adding two extra pieces to the output. Including current branch and repo directory.

2017-04-10 20:39 UTC, pdubb29 approved these changes

2017-04-10 20:54 UTC, kjjuno requested changes
Please fix the whitespace. This project uses spaces instead of tabs.

2017-04-11 16:59 UTC, kjjuno requested changes
This is looking pretty good!

The only problem is that now that I can see this.... I don't like it :-(

I really like the current branch detail, but printing the path over and over is feeling like information overload.

Will you please remove the code that prints the path to the dependency?

2017-04-11 23:24 UTC, kjjuno commented
As per our discussion, keep the branch display always. However, let's add a `-v, --verbose` option that will include the full path (and possibly other information). That way we can still get that information if wanted, but are not bombarded by so much information when it is not needed.

2017-04-12 17:08 UTC, kjjuno approved these changes

2017-04-12 17:08 UTC, merged